# Generated by Django 4.2.27 on 2026-02-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('scoring_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scoringalltime',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scoringcurrent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scoringtop',
            name='user',
        ),
    ]
