# Generated by Django 4.2.27 on 2026-02-04 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorings', '0002_scoring_remove_scoringalltime_user_and_more'),
        ('trainings', '0004_alter_trainingplanscoring_scoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoringAllTime',
        ),
        migrations.DeleteModel(
            name='ScoringCurrent',
        ),
        migrations.DeleteModel(
            name='ScoringTop',
        ),
        migrations.AddField(
            model_name='scoring',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
