# Generated by Django 4.2.27 on 2026-02-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorings', '0005_remove_scoring_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoring',
            name='value',
            field=models.IntegerField(default=1000),
        ),
    ]
