# Generated by Django 6.0 on 2025-12-16 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlanScoring',
            fields=[
                ('scoring_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('use_scoring', models.BooleanField(default=True)),
                ('scoring_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('public', models.BooleanField(default=False)),
                ('break_time', models.IntegerField(help_text='Break time in seconds')),
                ('order', models.JSONField(help_text='JSON list of exercise IDs defining the order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainingcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlanExercise',
            fields=[
                ('plan_exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainingplan')),
                ('scoring_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.trainingplanscoring')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingExerciseExecution',
            fields=[
                ('execution_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('repetitions', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('plan_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='trainings.trainingplanexercise')),
            ],
        ),
    ]
