# Generated by Django 6.0 on 2025-12-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorings', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplanscoring',
            name='scoring_id',
        ),
        migrations.AddField(
            model_name='trainingplanscoring',
            name='scoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scorings.scoringalltime'),
        ),
    ]
