# Generated by Django 6.0 on 2026-01-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_remove_trainingplanscoring_scoring_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplanexercise',
            name='order',
            field=models.JSONField(default=list, help_text='JSON list of exercise IDs defining the execution order'),
        ),
    ]
