# Generated by Django 4.2.27 on 2026-02-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorings', '0002_scoring_remove_scoringalltime_user_and_more'),
        ('trainings', '0003_trainingplanexercise_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplanscoring',
            name='scoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scorings.scoring'),
        ),
    ]
