# Generated by Django 4.2.27 on 2026-02-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
