# Generated by Django 4.2.27 on 2026-03-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tracking_type',
            field=models.CharField(choices=[('reps', 'Reps & Weight'), ('time', 'Time/Duration')], default='reps', max_length=20),
        ),
    ]
